### ISSUE TITLE
Execuation halts with error message: Error in plot.new() : figure margins too large

### ISSUE THREAD

**Issue by Pchaskar** [bzhanglab/WebGestaltR#25]
Error in plot.new() : figure margins too large
Calls: WebGestaltR ... plotEnrichmentPlot -> plot -> plot.default -> plot.new

**Comment by yxngl** [comment]
Can you try using `plotFormat="svg"`? Or `isOutput=FALSE` if you just need
the result data frame?

**Comment by iblacksand** [comment]
I also have seen this occur on the website, but when I reran the same analysis with no changes, the error message didn't appear. This was with GSEA with a list that was sensitive to the random walk and would change results, so I am guessing the error depends on the amount of enriched pathways/drugs/etc. This could probably be fixed by manually setting the margins.

**Comment by Pchaskar** [comment]
Thanks,

`gseaplotFormat="svg, solved the problem for me.

But I agree this issue occurs occasionally, and re-running resolves it.
